### ISSUE TITLE
Please add an option to enable "Windows is ready" back

### ISSUE THREAD

**Issue by ghost** [sindex/no-annoyance#3]
First of all, thank you for maintaining this extension! It's worked out well for me. However, as time goes, I've had workflow breaking issues with some applications stealing window focus when it's undesired. Could an option to reverse changes back to be added? Or at least, tell us how to re-enable it manually since no source of information about disabling "Windows is ready", mentions how to enable it back.

**Comment by jaller94** [comment]
Go to https://extensions.gnome.org/extension/1236/noannoyance/
There you can enable and disable the extension.
You can also remove it. In that case you will have to re-download it, if you wish to use it again.

**Comment by sashasimkin** [comment]
I think that this can be better resolved by adding whitelist of applications that can steal the focus (or blacklist of apps that are not allowed to).
